### ISSUE TITLE
Running xpms2d gives out "can't open display error"

### ISSUE THREAD

**Issue by bchen112** [NCAR/aircraft_oap#2]
Programs build is now successful, however xpms2d gives out "can't open display error". The other programs like oapinfo and padsinfo are working.

**Comment by topher800** [comment]
Looks like system must be restarted after installing XQuartz.

**Comment by bchen112** [comment]
Ok! I just restarted it and it’s updating. I’ll get back to you later.
Thank you so much for your help!

**Comment by bchen112** [comment]
ok, it totally works now!

**Comment by topher800** [comment]
Excellent!  Hope the program works to your satisfaction.

**Comment by bchen112** [comment]
The images of the ice particles are lovely!
